language: python
python:
  - "3.7"
install:
  # update is required to update the repositories to see the new packages for
  # Docker.
  - sudo apt-get update
  - pip install -r requirements.txt

script:
  - coverage erase
  - coverage run --rcfile=.coveragerc tests.py
  - coverage combine
  - coverage report -m
  - codecov